# Generated by Django 6.0.3 on 2026-04-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('failed', 'Failed')], default='training', max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='welcome_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_color', models.CharField(default='#3b82f6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.bot')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.IntegerField(default=0)),
                ('pages_scraped', models.IntegerField(default=0)),
                ('chunks_created', models.IntegerField(default=0)),
                ('status_message', models.TextField(default='Initializing...')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_status', to='core.bot')),
            ],
        ),
    ]
