# Generated by Django 6.0.3 on 2026-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bot_status_bot_welcome_message_botconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='chunks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapedpage',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
