# Generated by Django 6.0.3 on 2026-04-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scrapedpage_chunks_count_alter_scrapedpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='position',
            field=models.CharField(default='right', max_length=10),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='bot_color',
            field=models.CharField(default='#4F46E5', max_length=20),
        ),
    ]
